#!/bin/sh

set -e

. /usr/share/debconf/confmodule

#db_input high osm-tile-server/path || true
db_input medium osm-tile-server/db-name || true
db_input medium osm-tile-server/db-user || true
db_input medium osm-tile-server/db-password || true
db_input medium osm-tile-server/root-password || true
db_input medium osm-tile-server/enable || true
db_go

exit 0
