default:

install:
	mkdir -p ${DESTDIR}/usr/bin
	install osm-tile-server-process ${DESTDIR}/usr/bin/
	install osm-tile-server-status ${DESTDIR}/usr/bin/
	install osm-tile-server-download ${DESTDIR}/usr/bin/
	install osm-tile-server-import ${DESTDIR}/usr/bin/
