#!/bin/bash

no_permission(){
    echo "You do not have permission to run this command."
    echo "Run as 'root' or add yourself to the group:"
    echo "  'osm-tile-server'"
}

umask 002

ALLOWED=0

WHO=`whoami`
if [ "$WHO" = "root" ] || [ "$WHO" = "osm-tile-server" ] ; then
    ALLOWED=1
fi

if groups | grep -q '\bosm-tile-server\b' ; then
    ALLOWED=1
fi

if [ $ALLOWED = 1 ] ;then
  /usr/lib/osm-tile-server-base/bin/osm-tile-server-import-raw $*
else
  no_permission
fi

