#!/bin/bash

umask 002

FILENAME="downloaded.osm.pbf"
URL="http://download.geofabrik.de/europe/norway-latest.osm.pbf"
COMMAND="wget -O /var/cache/osm-tile-server-base/${FILENAME} ${URL}"
echo "The following command will be run to download:\n\n"
echo " ${COMMAND}\n\n"

$COMMAND


