#!/bin/bash

set -e

set +e
cat /var/cache/osm-tile-server-base/status.txt | grep -q TODO
RET=$?
set -e
if [ "$RET" = "0" ] ; then
    osm-tile-server-download Norway
    osm-tile-server-import /var/cache/osm-tile-server-base/downloaded.osm.pbf
    osm-tile-server-status done
fi
