#!/bin/bash

no_permission(){
    echo "You do not have permission to run this command."
    echo "Run as 'root' or add yourself to the group:"
    echo "  'osm-tile-server'"
}

umask 002
PATH=$PATH:/usr/lib/osm-tile-server-base/bin

ALLOWED=0

WHO=`whoami`
if [ "$WHO" = "root" ] || [ "$WHO" = "osm-tile-server" ] ; then
    ALLOWED=1
fi

if groups | grep -q '\bosm-tile-server\b' ; then
    ALLOWED=1
fi

if [ $ALLOWED = 0 ] ;then
    no_permission
    exit -1
fi

failed(){
    echo "Failed"
    osm-tile-server-status todo
    exit -1
}
trap failed SIGINT
trap failed SIGTERM

set -e

set +e
cat /var/lib/osm-tile-server-base/status.txt | grep -q TODO
RET=$?
set -e
if [ "$RET" = "0" ] ; then
    osm-tile-server-status inprogress
    osm-tile-server-download
    osm-tile-server-import /var/cache/osm-tile-server-base/downloaded.osm.pbf
    osm-tile-server-status done
else
    echo "Nothing to do"
    echo "Run \"sudo dpkg-reconfigure osm-tile-server-base\" to configure OSM tile server"
fi
